use_frameworks!
platform :ios, '8.0'

install! 'cocoapods', :deterministic_uuids => false

target 'WtCore_Example' do
  pod 'WtCore', :path => '../'

  target 'WtCore_Tests' do
    inherit! :search_paths
    
  end
end
