use_frameworks!
platform :ios, '8.0'

install! 'cocoapods', :deterministic_uuids => false

target 'WtCore_Example' do
  pod 'WtCore', :path => '../'

  target 'WtCore_Tests' do
    inherit! :search_paths
    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if !target.name.start_with?('WtCore')
            target.build_configurations.each do |config|
                config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
            end
        end
    end
end
